# Site settings
title: 会写代码的产品汪
SEOTitle: 向海燕的博客 | Xhy Blog
header-img: img/home-bg.jpg
email: xianghaiyan_it@163.com
description: "关于前端与设计、程序猿与产品汪 | 向海燕，& Mobile Lover，Product Manager | 这里是向海燕的个人博客"
keyword: "向海燕, 向海燕的博客, Xhy Blog, 博客, 个人网站, 互联网, 前端, 设计, 产品"
url: "http://www.58lhh.com"              # your host, for absolute URL
baseurl: " "         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     petrelxiang
zhihu_username:     petrelxiang
github_username:    xianghaiyan
facebook_username:  petrelxiang



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 6
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: petrelxiang
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 1b6cc67b3c5be75f002de40289c2e413
# Google Analytics
ga_track_id: 'UA-86882698-1'            # Format: UA-xxxxxx-xx
ga_domain: 58lhh.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，做做设计，看看产品。世界那么大，我还很年轻。"
sidebar-avatar: /img/avatar-xhy.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me"
    },{
        title: "Foo",
        href: "#"
    },{
        title: "Bar",
        href: "#"
    },{
        title: "Example Friends",
        href: "#"
    },{
        title: "It helps SEO",
        href: "#"
    }
]
